// <auto-generated />
using System;
using CMPlus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMPlus.Infrastructure.Migrations
{
    [DbContext(typeof(CmPlusDbContext))]
    [Migration("20260810105012_Sprint11_DB01_IndexTuning")]
    partial class Sprint11_DB01_IndexTuning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMPlus.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ActualFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("BudgetCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("FreeFloat")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LatestProgressPeriodEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LatestProgressRecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("PlannedFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PlannedStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalFloat")
                        .HasColumnType("int");

                    b.Property<Guid>("WbsNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WbsNodeId");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activities_BudgetCost", "[BudgetCost] >= 0");

                            t.HasCheckConstraint("CK_Activities_DurationDays", "[DurationDays] >= 0");

                            t.HasCheckConstraint("CK_Activities_ProgressPercentage", "[ProgressPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActivityProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("PeriodEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TenantId", "PeriodEndDate");

                    b.HasIndex("TenantId", "ActivityId", "PeriodEndDate")
                        .IsDescending(false, false, true);

                    b.ToTable("ActivityProgressLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActivityProgressLogs_ActualQuantity", "[ActualQuantity] >= 0");

                            t.HasCheckConstraint("CK_ActivityProgressLogs_ProgressPercentage", "[ProgressPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActivityRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LagDays")
                        .HasColumnType("int");

                    b.Property<Guid>("PredecessorActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.Property<Guid>("SuccessorActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PredecessorActivityId");

                    b.HasIndex("TenantId", "SuccessorActivityId");

                    b.ToTable("ActivityRelations", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActualCostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CostCategory")
                        .HasColumnType("int");

                    b.Property<string>("CostCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FileImportJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IncurredDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("PaidDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("WbsNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("FileImportJobId");

                    b.HasIndex("ReversesEntryId");

                    b.HasIndex("WbsNodeId");

                    b.HasIndex("TenantId", "ActivityId", "IncurredDate")
                        .HasFilter("[ActivityId] IS NOT NULL");

                    b.HasIndex("TenantId", "ProjectId", "IncurredDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "ProjectId", "IncurredDate"), new[] { "Amount" });

                    b.HasIndex("TenantId", "WbsNodeId", "IncurredDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "WbsNodeId", "IncurredDate"), new[] { "Amount" });

                    b.HasIndex("TenantId", "ProjectId", "CostCategory", "IncurredDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "ProjectId", "CostCategory", "IncurredDate"), new[] { "Amount" });

                    b.ToTable("ActualCostEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActualCostEntries_Amount_NotZero", "[Amount] <> 0");

                            t.HasCheckConstraint("CK_ActualCostEntries_Quantity", "[Quantity] IS NULL OR [Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("ActorRoleAtTime")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalPolicyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DocumentType", "DocumentId", "RevisionNo", "StepNo");

                    b.ToTable("ApprovalActions", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSelfApproval")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CumulativeVoEscalationPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("CumulativeVoEscalationRole")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "DocumentType")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ApprovalPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalPolicies_CumulativeVoEscalationPct", "[CumulativeVoEscalationPct] IS NULL OR [CumulativeVoEscalationPct] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuorumCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredRole")
                        .HasColumnType("int");

                    b.Property<Guid?>("RequiredUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalPolicyId");

                    b.HasIndex("TenantId", "ApprovalPolicyId", "StepNo");

                    b.ToTable("ApprovalPolicyRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalPolicyRules_MaxAmount", "[MaxAmount] IS NULL OR [MaxAmount] > [MinAmount]");

                            t.HasCheckConstraint("CK_ApprovalPolicyRules_MinAmount", "[MinAmount] >= 0");

                            t.HasCheckConstraint("CK_ApprovalPolicyRules_QuorumCount", "[QuorumCount] >= 1");

                            t.HasCheckConstraint("CK_ApprovalPolicyRules_StepNo", "[StepNo] >= 1");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("TenantId", "EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId");

                    b.ToTable("Calendars", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CalendarException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("TenantId", "CalendarId");

                    b.ToTable("CalendarExceptions", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CpmRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ProjectDurationDays")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "CalculatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("CpmRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_CpmRuns_ProjectDurationDays", "[ProjectDurationDays] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CpmRunActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CpmRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("EarlyFinish")
                        .HasColumnType("int");

                    b.Property<int>("EarlyStart")
                        .HasColumnType("int");

                    b.Property<int>("FreeFloat")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int>("LateFinish")
                        .HasColumnType("int");

                    b.Property<int>("LateStart")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalFloat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CpmRunId");

                    b.HasIndex("TenantId", "CpmRunId");

                    b.ToTable("CpmRunActivities", null, t =>
                        {
                            t.HasCheckConstraint("CK_CpmRunActivities_DurationDays", "[DurationDays] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CpmRunRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CpmRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LagDays")
                        .HasColumnType("int");

                    b.Property<Guid>("PredecessorActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.Property<Guid>("SuccessorActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CpmRunId");

                    b.HasIndex("TenantId", "CpmRunId");

                    b.ToTable("CpmRunRelations", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.DailyWeatherLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("ConditionNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("CorrectsWeatherLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntryKind")
                        .HasColumnType("int");

                    b.Property<decimal?>("HoursLost")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("ImpactNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LogDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RainfallMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorrectsWeatherLogId");

                    b.HasIndex("TenantId", "CorrectsWeatherLogId")
                        .IsUnique()
                        .HasFilter("[CorrectsWeatherLogId] IS NOT NULL");

                    b.HasIndex("TenantId", "ProjectId", "LogDate", "RecordedAt")
                        .IsDescending(false, false, true, true);

                    b.ToTable("DailyWeatherLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyWeatherLogs_HoursLost", "[HoursLost] IS NULL OR [HoursLost] BETWEEN 0 AND 24");

                            t.HasCheckConstraint("CK_DailyWeatherLogs_RainfallMm", "[RainfallMm] IS NULL OR [RainfallMm] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.DailyWeatherLogActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DailyWeatherLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("DailyWeatherLogId");

                    b.HasIndex("TenantId", "ActivityId");

                    b.HasIndex("TenantId", "DailyWeatherLogId", "ActivityId")
                        .IsUnique();

                    b.ToTable("DailyWeatherLogActivities", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AsScheduledDurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("ConcurrencyAssessed")
                        .HasColumnType("bit");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<int>("CountableStoppageDayCount")
                        .HasColumnType("int");

                    b.Property<int>("CriticalityBasis")
                        .HasColumnType("int");

                    b.Property<int>("DistinctCountableDateCount")
                        .HasColumnType("int");

                    b.Property<bool>("EntitlementBasisAssessed")
                        .HasColumnType("bit");

                    b.Property<int>("EotEligibleDays")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EvaluatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImpactedDurationDays")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LatestNoticeDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("NoticeWindowExpired")
                        .HasColumnType("bit");

                    b.Property<string>("PolicySnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnattributedStoppageDayCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "EvaluatedAt");

                    b.ToTable("EotEvaluations", null, t =>
                        {
                            t.HasCheckConstraint("CK_EotEvaluations_Counts", "[CountableStoppageDayCount] >= 0 AND [DistinctCountableDateCount] >= 0 AND [UnattributedStoppageDayCount] >= 0");

                            t.HasCheckConstraint("CK_EotEvaluations_Durations", "[AsScheduledDurationDays] >= 0 AND [ImpactedDurationDays] >= 0 AND [EotEligibleDays] >= 0");

                            t.HasCheckConstraint("CK_EotEvaluations_Window", "[WindowEnd] >= [WindowStart]");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluationDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("CpmRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EotEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IndicativeEotDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnImpactedCriticalPath")
                        .HasColumnType("bit");

                    b.Property<int>("MarginalEotDays")
                        .HasColumnType("int");

                    b.Property<int>("RemainingFloatAfter")
                        .HasColumnType("int");

                    b.Property<int>("StoppageDays")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalFloatAtRun")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnclaimedFractionalHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("WasCriticalAtRun")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EotEvaluationId");

                    b.HasIndex("TenantId", "EotEvaluationId");

                    b.ToTable("EotEvaluationDrivers", null, t =>
                        {
                            t.HasCheckConstraint("CK_EotEvaluationDrivers_Counts", "[StoppageDays] >= 0 AND [IndicativeEotDays] >= 0 AND [MarginalEotDays] >= 0 AND [RemainingFloatAfter] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AsScheduledDurationDays")
                        .HasColumnType("int");

                    b.Property<Guid>("CpmRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeltaDays")
                        .HasColumnType("int");

                    b.Property<Guid>("EotEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImpactedDurationDays")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("WindowFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EotEvaluationId");

                    b.HasIndex("TenantId", "CpmRunId");

                    b.HasIndex("TenantId", "EotEvaluationId");

                    b.ToTable("EotEvaluationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_EotEvaluationRuns_Window", "[WindowTo] >= [WindowFrom]");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluationSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CountableDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("DailyWeatherLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EotEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ExclusionReason")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EotEvaluationId");

                    b.HasIndex("TenantId", "DailyWeatherLogId");

                    b.HasIndex("TenantId", "EotEvaluationId");

                    b.ToTable("EotEvaluationSources", null, t =>
                        {
                            t.HasCheckConstraint("CK_EotEvaluationSources_CountableDays", "[CountableDays] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EvmPeriodSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Ac")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bac")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Eac")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EacVariant")
                        .HasColumnType("int");

                    b.Property<decimal?>("Etc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ev")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PerformanceFactor")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Pv")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Vac")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "DataDate")
                        .IsUnique();

                    b.ToTable("EvmPeriodSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvmPeriodSnapshots_Bac", "[Bac] >= 0");

                            t.HasCheckConstraint("CK_EvmPeriodSnapshots_Ev", "[Ev] >= 0");

                            t.HasCheckConstraint("CK_EvmPeriodSnapshots_Pv", "[Pv] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.FileImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "StartedAt");

                    b.ToTable("FileImportJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileImportJobs_RowsImported", "[RowsImported] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.IssueLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "CreatedAt");

                    b.HasIndex("TenantId", "ProjectId", "Status");

                    b.ToTable("IssueLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_IssueLogs_ClosedAt_Matches_Status", "([Status] = 3 AND [ClosedAt] IS NOT NULL) OR ([Status] <> 3 AND [ClosedAt] IS NULL)");

                            t.HasCheckConstraint("CK_IssueLogs_StartedAt_Before_ClosedAt", "[StartedAt] IS NULL OR [ClosedAt] IS NULL OR [StartedAt] <= [ClosedAt]");

                            t.HasCheckConstraint("CK_IssueLogs_StartedAt_Matches_Status", "([Status] IN (2, 3) AND [StartedAt] IS NOT NULL) OR ([Status] = 1 AND [StartedAt] IS NULL)");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.PaymentCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualProgressPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AdvanceRecoveryAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AllowSelfApproval")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ApprovalPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApprovalPolicyVersion")
                        .HasColumnType("int");

                    b.Property<decimal>("ApprovePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset?>("CertifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ClaimPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStepNo")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GrossCertifiedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("LastVoteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MilestoneNo")
                        .HasColumnType("int");

                    b.Property<decimal>("MilestoneValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("PreviousCumulativeApprovePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RetentionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "MilestoneNo");

                    b.HasIndex("TenantId", "ProjectId", "Status");

                    b.ToTable("PaymentCertificates", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentCertificates_ApprovePct", "[ApprovePct] >= 0 AND [ApprovePct] <= 100");

                            t.HasCheckConstraint("CK_PaymentCertificates_GrossCertifiedAmount", "[GrossCertifiedAmount] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.PaymentCertificateApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuorumCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredRole")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCertificateId");

                    b.HasIndex("TenantId", "PaymentCertificateId", "RevisionNo", "StepNo")
                        .IsUnique();

                    b.ToTable("PaymentCertificateApprovalSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentCertificateApprovalSteps_QuorumCount", "[QuorumCount] >= 1");

                            t.HasCheckConstraint("CK_PaymentCertificateApprovalSteps_RevisionNo", "[RevisionNo] >= 1");

                            t.HasCheckConstraint("CK_PaymentCertificateApprovalSteps_StepNo", "[StepNo] >= 1");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AdvanceAmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AdvanceRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AdvanceRecoveryEndPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AdvanceRecoveryMethod")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdvanceRecoveryRatePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AdvanceRecoveryStartPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ApprovedVariationOrderCount")
                        .HasColumnType("int");

                    b.Property<decimal>("BAC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ContractFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ContractStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DefectsLiabilityMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("EacCustomPerformanceFactor")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("EacManualEtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("EacManualEtcStaleSince")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EacVariantDefault")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("OriginalBac")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("RetentionCapPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RetentionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RetentionRelease1Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Projects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Projects_AdvanceAmountPaid", "[AdvanceAmountPaid] >= 0");

                            t.HasCheckConstraint("CK_Projects_AdvanceRate", "[AdvanceRate] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_AdvanceRecoveryEndPct", "[AdvanceRecoveryEndPct] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_AdvanceRecoveryRatePct", "[AdvanceRecoveryRatePct] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_AdvanceRecoveryStartPct", "[AdvanceRecoveryStartPct] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_ApprovedVariationOrderCount", "[ApprovedVariationOrderCount] >= 0");

                            t.HasCheckConstraint("CK_Projects_BAC", "[BAC] >= 0");

                            t.HasCheckConstraint("CK_Projects_ContractValue", "[ContractValue] >= 0");

                            t.HasCheckConstraint("CK_Projects_EacCustomPerformanceFactor", "[EacCustomPerformanceFactor] > 0");

                            t.HasCheckConstraint("CK_Projects_EacManualEtc", "[EacManualEtc] >= 0");

                            t.HasCheckConstraint("CK_Projects_OriginalBac", "[OriginalBac] >= 0");

                            t.HasCheckConstraint("CK_Projects_OriginalContractValue", "[OriginalContractValue] >= 0");

                            t.HasCheckConstraint("CK_Projects_RetentionCapPercentage", "[RetentionCapPercentage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_RetentionRate", "[RetentionRate] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_RetentionRelease1Percentage", "[RetentionRelease1Percentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ProjectEotPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CountUnmeasuredRainfallWhenThresholdSet")
                        .HasColumnType("bit");

                    b.Property<decimal>("FullDayHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("MinHoursLostForCountableDay")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("MinRainfallMmForCountableDay")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("NoticePeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("PartialDayPolicy")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectEotPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectEotPolicies_FullDayHours", "[FullDayHours] > 0 AND [FullDayHours] <= 24");

                            t.HasCheckConstraint("CK_ProjectEotPolicies_MinHoursLostForCountableDay", "[MinHoursLostForCountableDay] >= 0 AND [MinHoursLostForCountableDay] <= 24");

                            t.HasCheckConstraint("CK_ProjectEotPolicies_MinRainfallMmForCountableDay", "[MinRainfallMmForCountableDay] IS NULL OR [MinRainfallMmForCountableDay] >= 0");

                            t.HasCheckConstraint("CK_ProjectEotPolicies_NoticePeriodDays", "[NoticePeriodDays] IS NULL OR [NoticePeriodDays] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ProjectFinanceLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PaymentCertificateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCertificateId");

                    b.HasIndex("TenantId", "ProjectId", "Category");

                    b.ToTable("ProjectFinanceLedgers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectFinanceLedgers_Amount_NotZero", "[Amount] <> 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.VariationOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSelfApproval")
                        .HasColumnType("bit");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ApprovalPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApprovalPolicyVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("BacAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BacBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractValueAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractValueBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CumulativeVoPctAtApproval")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("CurrentStepNo")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("EscalationBasisContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Justification")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("LastVoteAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeImpactDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<string>("VoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId")
                        .HasDatabaseName("IX_VariationOrders_TenantId_ProjectId_Approved")
                        .HasFilter("[Status] = 3");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "ProjectId"), new[] { "Amount" });

                    b.HasIndex("TenantId", "ProjectId", "Status");

                    b.HasIndex("TenantId", "ProjectId", "VoNumber")
                        .IsUnique();

                    b.ToTable("VariationOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_VariationOrders_CurrentStepNo", "[CurrentStepNo] >= 0");

                            t.HasCheckConstraint("CK_VariationOrders_RevisionNo", "[RevisionNo] >= 1");

                            t.HasCheckConstraint("CK_VariationOrders_TotalSteps", "[TotalSteps] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.VariationOrderApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuorumCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredRole")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariationOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VariationOrderId");

                    b.HasIndex("TenantId", "VariationOrderId", "RevisionNo", "StepNo")
                        .IsUnique();

                    b.ToTable("VariationOrderApprovalSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_VariationOrderApprovalSteps_QuorumCount", "[QuorumCount] >= 1");

                            t.HasCheckConstraint("CK_VariationOrderApprovalSteps_RevisionNo", "[RevisionNo] >= 1");

                            t.HasCheckConstraint("CK_VariationOrderApprovalSteps_StepNo", "[StepNo] >= 1");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.VariationOrderScopeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BudgetCostDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariationOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VariationOrderId");

                    b.HasIndex("TenantId", "ActivityId");

                    b.HasIndex("TenantId", "VariationOrderId");

                    b.ToTable("VariationOrderScopeItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_VariationOrderScopeItems_BudgetCostDelta_NotZero", "[BudgetCostDelta] <> 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.WBSNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentWbsNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("WeightPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParentWbsNodeId");

                    b.HasIndex("TenantId", "ProjectId", "ParentWbsNodeId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "ProjectId", "ParentWbsNodeId"), new[] { "Code", "Title", "WeightPercentage" });

                    b.ToTable("WBSNodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_WBSNodes_WeightPercentage", "[WeightPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActivityProgressLog", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActualCostEntry", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CMPlus.Domain.Entities.FileImportJob", null)
                        .WithMany()
                        .HasForeignKey("FileImportJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CMPlus.Domain.Entities.ActualCostEntry", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CMPlus.Domain.Entities.WBSNode", null)
                        .WithMany()
                        .HasForeignKey("WbsNodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicyRule", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.ApprovalPolicy", null)
                        .WithMany("Rules")
                        .HasForeignKey("ApprovalPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CalendarException", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CpmRunActivity", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.CpmRun", null)
                        .WithMany("Activities")
                        .HasForeignKey("CpmRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CpmRunRelation", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.CpmRun", null)
                        .WithMany("Relations")
                        .HasForeignKey("CpmRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.DailyWeatherLog", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.DailyWeatherLog", null)
                        .WithMany()
                        .HasForeignKey("CorrectsWeatherLogId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.DailyWeatherLogActivity", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMPlus.Domain.Entities.DailyWeatherLog", null)
                        .WithMany("AffectedActivities")
                        .HasForeignKey("DailyWeatherLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluationDriver", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.EotEvaluation", null)
                        .WithMany("Drivers")
                        .HasForeignKey("EotEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluationRun", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.EotEvaluation", null)
                        .WithMany("Runs")
                        .HasForeignKey("EotEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluationSource", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.EotEvaluation", null)
                        .WithMany("Sources")
                        .HasForeignKey("EotEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.PaymentCertificateApprovalStep", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.PaymentCertificate", null)
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("PaymentCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ProjectFinanceLedger", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.PaymentCertificate", null)
                        .WithMany()
                        .HasForeignKey("PaymentCertificateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.VariationOrderApprovalStep", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.VariationOrder", null)
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("VariationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.VariationOrderScopeItem", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.VariationOrder", null)
                        .WithMany("ScopeItems")
                        .HasForeignKey("VariationOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.WBSNode", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.WBSNode", null)
                        .WithMany()
                        .HasForeignKey("ParentWbsNodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CpmRun", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Relations");
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.DailyWeatherLog", b =>
                {
                    b.Navigation("AffectedActivities");
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.EotEvaluation", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Runs");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.PaymentCertificate", b =>
                {
                    b.Navigation("ApprovalSteps");
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.VariationOrder", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("ScopeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
