// <auto-generated />
using System;
using CMPlus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMPlus.Infrastructure.Migrations
{
    [DbContext(typeof(CmPlusDbContext))]
    partial class CmPlusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMPlus.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ActualFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("BudgetCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("FreeFloat")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LatestProgressPeriodEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LatestProgressRecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("PlannedFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PlannedStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalFloat")
                        .HasColumnType("int");

                    b.Property<Guid>("WbsNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WbsNodeId");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activities_BudgetCost", "[BudgetCost] >= 0");

                            t.HasCheckConstraint("CK_Activities_DurationDays", "[DurationDays] >= 0");

                            t.HasCheckConstraint("CK_Activities_ProgressPercentage", "[ProgressPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActivityProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("PeriodEndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ProgressPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TenantId", "PeriodEndDate");

                    b.HasIndex("TenantId", "ActivityId", "PeriodEndDate")
                        .IsDescending(false, false, true);

                    b.ToTable("ActivityProgressLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActivityProgressLogs_ActualQuantity", "[ActualQuantity] >= 0");

                            t.HasCheckConstraint("CK_ActivityProgressLogs_ProgressPercentage", "[ProgressPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActivityRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LagDays")
                        .HasColumnType("int");

                    b.Property<Guid>("PredecessorActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RelationType")
                        .HasColumnType("int");

                    b.Property<Guid>("SuccessorActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PredecessorActivityId");

                    b.HasIndex("TenantId", "SuccessorActivityId");

                    b.ToTable("ActivityRelations", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ActedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("ActorRoleAtTime")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalPolicyVersion")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DocumentType", "DocumentId", "RevisionNo", "StepNo");

                    b.ToTable("ApprovalActions", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSelfApproval")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CumulativeVoEscalationPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("CumulativeVoEscalationRole")
                        .HasColumnType("int");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "DocumentType")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ApprovalPolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalPolicies_CumulativeVoEscalationPct", "[CumulativeVoEscalationPct] IS NULL OR [CumulativeVoEscalationPct] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovalPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuorumCount")
                        .HasColumnType("int");

                    b.Property<int>("RequiredRole")
                        .HasColumnType("int");

                    b.Property<Guid?>("RequiredUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalPolicyId");

                    b.HasIndex("TenantId", "ApprovalPolicyId", "StepNo");

                    b.ToTable("ApprovalPolicyRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalPolicyRules_MaxAmount", "[MaxAmount] IS NULL OR [MaxAmount] > [MinAmount]");

                            t.HasCheckConstraint("CK_ApprovalPolicyRules_MinAmount", "[MinAmount] >= 0");

                            t.HasCheckConstraint("CK_ApprovalPolicyRules_QuorumCount", "[QuorumCount] >= 1");

                            t.HasCheckConstraint("CK_ApprovalPolicyRules_StepNo", "[StepNo] >= 1");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("TenantId", "EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId");

                    b.ToTable("Calendars", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CalendarException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("TenantId", "CalendarId");

                    b.ToTable("CalendarExceptions", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.FileImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProjectId", "StartedAt");

                    b.ToTable("FileImportJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileImportJobs_RowsImported", "[RowsImported] >= 0");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AdvanceAmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AdvanceRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AdvanceRecoveryEndPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AdvanceRecoveryMethod")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdvanceRecoveryRatePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AdvanceRecoveryStartPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BAC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ContractFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ContractStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("ContractValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("DataDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DefectsLiabilityMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("EacCustomPerformanceFactor")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("EacManualEtc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EacVariantDefault")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("RetentionCapPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RetentionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RetentionRelease1Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Projects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Projects_AdvanceAmountPaid", "[AdvanceAmountPaid] >= 0");

                            t.HasCheckConstraint("CK_Projects_AdvanceRate", "[AdvanceRate] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_AdvanceRecoveryEndPct", "[AdvanceRecoveryEndPct] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_AdvanceRecoveryRatePct", "[AdvanceRecoveryRatePct] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_AdvanceRecoveryStartPct", "[AdvanceRecoveryStartPct] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_BAC", "[BAC] >= 0");

                            t.HasCheckConstraint("CK_Projects_ContractValue", "[ContractValue] >= 0");

                            t.HasCheckConstraint("CK_Projects_EacCustomPerformanceFactor", "[EacCustomPerformanceFactor] > 0");

                            t.HasCheckConstraint("CK_Projects_EacManualEtc", "[EacManualEtc] >= 0");

                            t.HasCheckConstraint("CK_Projects_RetentionCapPercentage", "[RetentionCapPercentage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_RetentionRate", "[RetentionRate] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Projects_RetentionRelease1Percentage", "[RetentionRelease1Percentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.WBSNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentWbsNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("WeightPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParentWbsNodeId");

                    b.HasIndex("TenantId", "ProjectId", "ParentWbsNodeId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "ProjectId", "ParentWbsNodeId"), new[] { "Code", "Title", "WeightPercentage" });

                    b.ToTable("WBSNodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_WBSNodes_WeightPercentage", "[WeightPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ActivityProgressLog", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicyRule", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.ApprovalPolicy", null)
                        .WithMany("Rules")
                        .HasForeignKey("ApprovalPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.CalendarException", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.Calendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.WBSNode", b =>
                {
                    b.HasOne("CMPlus.Domain.Entities.WBSNode", null)
                        .WithMany()
                        .HasForeignKey("ParentWbsNodeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CMPlus.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
