import { generateOutboxId } from './idGenerator'
import type { OutboxStorageAdapter } from './storage'
import type { EnqueueOutboxItemInput, OutboxItem, OutboxItemStatus, OutboxOwner } from './types'

export interface CreateOutboxStoreOptions {
  storage: OutboxStorageAdapter
  /**
   * Resolves the *current* session's owner, or `null` if nobody is authenticated. Called fresh on
   * every `enqueue`/`list`/`pending`/`reconcileInterruptedSyncs` — never memoized at construction —
   * so a session change (a different user logging in, even into a store instance that somehow
   * outlives the switch) is honoured immediately, not only after a remount. Real callers pass
   * `services/outbox/authOwner.ts`'s `getCurrentOutboxOwner`; tests inject a fixed owner. See H-02,
   * Sprint 12 security review.
   */
  getOwner: () => OutboxOwner | null
  /** Injectable for tests; defaults to `() => new Date().toISOString()`. */
  now?: () => string
  /** Injectable for tests; defaults to `generateOutboxId` (real UUIDs). */
  generateId?: () => string
}

/** Thrown by `enqueue` when there is no authenticated session to attribute the write to. Should be
 * unreachable in practice (every outbox-backed screen sits behind `RequireAuth`), but `enqueue`
 * fails loud rather than silently minting an ownerless record that no session could ever see again. */
export class OutboxOwnerRequiredError extends Error {
  constructor() {
    super('ไม่พบผู้ใช้ที่เข้าสู่ระบบ ไม่สามารถบันทึกรายการนี้ได้ กรุณาเข้าสู่ระบบใหม่')
    this.name = 'OutboxOwnerRequiredError'
  }
}

/** True only when `item` carries a well-formed owner matching `owner` exactly. A record missing (or
 * malformed on) `ownerUserId`/`ownerTenantId` — e.g. one written by a pre-H-02 build of this app —
 * fails this check for *every* owner, deliberately: an unattributable record must never be shown to,
 * or flushed on behalf of, anyone (fail closed, not open). */
function isOwnedBy(item: OutboxItem, owner: OutboxOwner): boolean {
  return (
    typeof item.ownerUserId === 'string' &&
    typeof item.ownerTenantId === 'string' &&
    item.ownerUserId === owner.userId &&
    item.ownerTenantId === owner.tenantId
  )
}

/** `queued`/`failed` are both "still needs to go out" — `syncEngine.ts#flush` treats them
 * identically as its retry set. Exported so callers (e.g. a "รายการค้างซิงค์" counter) do not
 * duplicate this list. */
export const PENDING_STATUSES: readonly OutboxItemStatus[] = ['queued', 'failed']

/** Recorded as `lastError` on an item `reconcileInterruptedSyncs` finds still `syncing` at a fresh
 * session's startup — see that function's own doc comment for why this can only mean the previous
 * session ended (tab/app killed, phone locked and backgrounded, page reloaded) while the upload was
 * genuinely in flight, never a normal outcome. */
export const INTERRUPTED_SYNC_ERROR =
  'การซิงค์ถูกขัดจังหวะ (แอปถูกปิดหรือโหลดหน้าใหม่ระหว่างอัปโหลด) — ระบบจะลองใหม่โดยอัตโนมัติ'

/**
 * The outbox's storage-agnostic business logic (S12-FE-01, ADR-0005) — status transitions,
 * idempotency-key minting, timestamps. Written entirely against `OutboxStorageAdapter`, never
 * against IndexedDB directly, so it is unit-testable with `storage.inMemory.ts`'s in-memory double
 * and reusable unchanged once S13-FE-01 adds non-photo `kind`s.
 */
export function createOutboxStore(options: CreateOutboxStoreOptions) {
  const { storage, getOwner } = options
  const now = options.now ?? (() => new Date().toISOString())
  const generateId = options.generateId ?? generateOutboxId

  async function enqueue<TPayload>(input: EnqueueOutboxItemInput<TPayload>): Promise<OutboxItem<TPayload>> {
    const owner = getOwner()
    if (!owner) throw new OutboxOwnerRequiredError()

    const timestamp = now()
    const item: OutboxItem<TPayload> = {
      id: generateId(),
      kind: input.kind,
      // Minted once, here, never regenerated by a later retry (`markFailed`/`markSyncing` below
      // never touch it) — see `types.ts`'s remarks on why this cannot wait for S13-BE-01.
      idempotencyKey: generateId(),
      // Bound to the record at write time (H-02 fix) — never re-derived later, so a subsequent
      // session change can never retroactively reassign an already-queued item's ownership.
      ownerUserId: owner.userId,
      ownerTenantId: owner.tenantId,
      payload: input.payload,
      blob: input.blob ?? null,
      blobFileName: input.blobFileName ?? null,
      blobContentType: input.blobContentType ?? null,
      status: 'queued',
      attemptCount: 0,
      lastError: null,
      createdAt: timestamp,
      updatedAt: timestamp,
      syncedAt: null,
      serverId: null,
    }
    await storage.put(item)
    return item
  }

  /**
   * Every read in this module goes through here — the single owner-scoping choke point (H-02 fix).
   * `getOwner()` is re-resolved on every call, never cached, so it always reflects *this* call's
   * session. No owner (nobody authenticated) returns an empty list rather than throwing: several
   * call sites (`reconcileInterruptedSyncs` at mount, `usePhotoOutbox.ts#reload`) run during normal
   * transient states (e.g. immediately after a forced logout) where "show nothing" is the only safe
   * answer.
   */
  async function list(kind?: string): Promise<OutboxItem[]> {
    const owner = getOwner()
    const items = await storage.list(kind)
    const scoped = owner ? items.filter((item) => isOwnedBy(item, owner)) : []
    // Oldest first — a site user expects "the photo I took first uploads first", and it keeps a
    // retry list stable/readable across re-renders.
    return [...scoped].sort((a, b) => a.createdAt.localeCompare(b.createdAt))
  }

  async function pending(kind?: string): Promise<OutboxItem[]> {
    const items = await list(kind)
    return items.filter((item) => PENDING_STATUSES.includes(item.status))
  }

  async function markSyncing(id: string): Promise<void> {
    const item = await storage.get(id)
    if (!item) return
    await storage.put({ ...item, status: 'syncing', updatedAt: now() })
  }

  async function markSynced(id: string, serverId: string): Promise<void> {
    const item = await storage.get(id)
    if (!item) return
    const timestamp = now()
    await storage.put({
      ...item,
      status: 'synced',
      serverId,
      syncedAt: timestamp,
      updatedAt: timestamp,
      lastError: null,
      // The blob (often hundreds of KB) has no purpose once the server has the bytes — drop it so a
      // long-lived outbox of synced items does not slowly fill the device's IndexedDB quota.
      blob: null,
    })
  }

  async function markFailed(id: string, errorMessage: string): Promise<void> {
    const item = await storage.get(id)
    if (!item) return
    await storage.put({
      ...item,
      status: 'failed',
      attemptCount: item.attemptCount + 1,
      lastError: errorMessage,
      updatedAt: now(),
    })
  }

  async function remove(id: string): Promise<void> {
    await storage.delete(id)
  }

  /**
   * Resets any item still `syncing` back to a retryable (`failed`, hence `pending()`-eligible) state.
   * Call this exactly once, per `kind`, at the start of a fresh session (S12-QA-01 fix) — e.g.
   * `usePhotoOutbox.ts`'s mount effect, before its first `reload()`/sync-trigger registration — never
   * mid-session.
   *
   * **Why `syncing` needs this at all**: `markSyncing` (above) persists `status: 'syncing'` to durable
   * storage *before* the upload request starts, and only `markSynced`/`markFailed` (also above) ever
   * move it out of that state again. If the session ends (tab/app killed, phone locked, page reloaded)
   * while an item sits at `syncing`, neither of those ever runs — and `PENDING_STATUSES` above
   * deliberately excludes `syncing`, so `pending()`/`flush()` will never look at it again. Without this
   * function, that item is orphaned forever: durably stuck showing "กำลังซิงค์..." while nothing ever
   * retries it — the exact "รูปหาย" (lost photo) failure `docs/10.`'s DoD forbids.
   *
   * **Why `failed` (with `attemptCount`/`lastError` bookkeeping via `markFailed`) rather than silently
   * back to `queued`**: this genuinely was an attempt, just one whose outcome this device can no
   * longer observe (the request itself is gone — nothing is still listening for its response) — so it
   * gets the same audit trail (`attemptCount`, a Thai `lastError`) any other failed attempt gets,
   * rather than pretending it was never tried. Functionally `failed` and `queued` are identical to
   * `PENDING_STATUSES`/`flush()`, so this is a bookkeeping choice, not a behavioural one.
   *
   * **Why this is call-once-at-startup, not a durable `syncing` -> `flush()`-tolerant redesign**: an
   * item genuinely `syncing` *within* a live session always corresponds to a real in-flight request
   * that session's own memory is still tracking — `syncEngine.ts#flush`'s own in-memory `syncing` guard
   * already makes a second concurrent `flush()` call within that session a safe no-op, so nothing
   * *within* a session should ever be calling this. Only a genuinely fresh session (this store having
   * just been constructed) can have `syncing` items with no live request behind them, which is exactly
   * what makes resetting them safe here specifically. Doing this on every store construction (as
   * opposed to some periodic/heuristic sweep) is deliberate: any `syncing` item at construction time is
   * unconditionally stale by the reasoning above, so there is no "too soon, it might still be genuinely
   * in flight" window to protect against.
   *
   * **Duplicate-upload risk**: a subsequent retry may race a not-actually-dead previous attempt in the
   * one scenario this reasoning does not cover — an SPA remount (not a real reload) of the hook that
   * owns this store while an old, still-running request from a previous mount is somehow still in
   * flight. That residual risk is the same one this outbox already accepts and documents for a
   * lost-response retry (`photo-offline.spec.ts`'s "residual gap" test) — the per-item `idempotencyKey`
   * (minted once at `enqueue`, never regenerated) is what bounds it until the server honours
   * `Idempotency-Key` (S13-BE-01), not a guarantee this function makes on its own.
   *
   * **Ownership (H-02 fix)**: sourced from `list(kind)`, so this only ever reconciles/revives items
   * owned by the *current* session — a stranded item left `syncing` by a *previous* user on a shared
   * device is invisible here and is never revived on someone else's behalf.
   */
  async function reconcileInterruptedSyncs(kind?: string): Promise<number> {
    const items = await list(kind)
    const stale = items.filter((item) => item.status === 'syncing')
    for (const item of stale) {
      await markFailed(item.id, INTERRUPTED_SYNC_ERROR)
    }
    return stale.length
  }

  return { enqueue, list, pending, markSyncing, markSynced, markFailed, remove, reconcileInterruptedSyncs }
}

export type OutboxStore = ReturnType<typeof createOutboxStore>
